# Generated by Django 4.2.30 on 2026-06-24 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestational_age_weeks', models.PositiveIntegerField()),
                ('target_fasting_glucose', models.PositiveIntegerField(default=95)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('glucose_level', models.PositiveIntegerField(help_text='mg/dL')),
                ('meal_context', models.CharField(choices=[('F', 'Fasting'), ('1B', '1-Hour Post-Breakfast'), ('2B', '2-Hour Post-Breakfast'), ('1L', '1-Hour Post-Lunch'), ('2L', '2-Hour Post-Lunch'), ('1D', '1-Hour Post-Dinner'), ('2D', '2-Hour Post-Dinner')], max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_logs', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['profile'], name='patients_gl_profile_105350_idx'), models.Index(fields=['timestamp'], name='patients_gl_timesta_c78052_idx')],
            },
        ),
    ]
