# Generated by Django 4.2.30 on 2026-06-24 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientprofile_glucoselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucosePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_for', models.DateTimeField(help_text='The timestamp this prediction is for')),
                ('predicted_value', models.FloatField(help_text='Predicted glucose level (mg/dL)')),
                ('model', models.CharField(default='moving_average', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-predicted_for'],
                'indexes': [models.Index(fields=['profile'], name='patients_gl_profile_de0136_idx'), models.Index(fields=['predicted_for'], name='patients_gl_predict_c22ebe_idx')],
            },
        ),
    ]
