# Generated by Django 4.2.30 on 2026-06-24 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_glucoseprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('spike', 'Glycemic spike detected'), ('anomaly', 'Statistical anomaly detected')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('glucose_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.glucoselog')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_alerts', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_profile'], name='patients_do_patient_50a1b2_idx'), models.Index(fields=['is_read'], name='patients_do_is_read_f7f666_idx'), models.Index(fields=['created_at'], name='patients_do_created_583fb2_idx')],
            },
        ),
    ]
