# Generated by Django 4.2.30 on 2026-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_doctoralert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glucoseprediction',
            options={'ordering': ['-target_timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='glucoseprediction',
            name='patients_gl_predict_c22ebe_idx',
        ),
        migrations.RenameField(
            model_name='glucoseprediction',
            old_name='predicted_for',
            new_name='target_timestamp',
        ),
        migrations.AlterField(
            model_name='glucoseprediction',
            name='predicted_value',
            field=models.IntegerField(help_text='Predicted glucose level (mg/dL)'),
        ),
        migrations.AddIndex(
            model_name='glucoseprediction',
            index=models.Index(fields=['target_timestamp'], name='patients_gl_target__7500f9_idx'),
        ),
    ]
