# Generated by Django 4.2.30 on 2026-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_glucoseprediction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='doctor_email',
            field=models.EmailField(blank=True, help_text='Email address of assigned doctor for critical alerts', max_length=254, null=True),
        ),
    ]
