# Generated by Django 4.2.30 on 2026-06-24 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patientprofile_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='e.g., Insulin Aspart, Metformin', max_length=100)),
                ('dosage', models.CharField(help_text='e.g., 10 units, 500mg', max_length=100)),
                ('scheduled_time', models.CharField(choices=[('before_breakfast', 'Before Breakfast'), ('after_breakfast', 'After Breakfast'), ('before_lunch', 'Before Lunch'), ('after_lunch', 'After Lunch'), ('before_dinner', 'Before Dinner'), ('after_dinner', 'After Dinner'), ('bedtime', 'Bedtime')], max_length=20)),
                ('taken', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of medication schedule')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['date', 'scheduled_time'],
                'indexes': [models.Index(fields=['profile', 'date'], name='patients_me_profile_757d21_idx'), models.Index(fields=['date'], name='patients_me_date_f5e80e_idx')],
                'unique_together': {('profile', 'medication_name', 'scheduled_time', 'date')},
            },
        ),
    ]
