# Generated by Django 4.2.30 on 2026-07-06 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_educationalcontent_blogpost_patient_comment_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='patients_pr_patient_73b707_idx'), models.Index(fields=['created_at'], name='patients_pr_created_15617b_idx')],
            },
        ),
    ]
