# Generated by Django 4.2.30 on 2026-07-07 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_labresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('diabetes', 'Patient with Diabetes'), ('prediabetes', 'Patient with Prediabetes'), ('risk', 'Risk of Developing Diabetes')], max_length=20)),
                ('diabetes_type', models.CharField(blank=True, choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('gestational', 'Gestational Diabetes')], max_length=20)),
                ('fasting_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('post_meal_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('insulin_use', models.BooleanField(blank=True, null=True)),
                ('oral_medication_use', models.BooleanField(blank=True, null=True)),
                ('medication_timing', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('medical_history', models.TextField(blank=True)),
                ('family_history_diabetes', models.BooleanField(blank=True, null=True)),
                ('high_bp_history', models.BooleanField(blank=True, null=True)),
                ('high_cholesterol_history', models.BooleanField(blank=True, null=True)),
                ('gestational_diabetes_history', models.BooleanField(blank=True, null=True)),
                ('pcos_history', models.BooleanField(blank=True, null=True)),
                ('dietary_habits', models.TextField(blank=True)),
                ('eating_habits', models.TextField(blank=True)),
                ('nutrition_assessment', models.TextField(blank=True)),
                ('food_allergies_or_intolerance', models.TextField(blank=True)),
                ('food_affordability_and_preparation', models.TextField(blank=True)),
                ('food_preference_and_culture', models.TextField(blank=True)),
                ('physical_activity_level', models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=20)),
                ('lifestyle_factors', models.TextField(blank=True)),
                ('sleep_quality', models.TextField(blank=True)),
                ('stress_level', models.TextField(blank=True)),
                ('alcohol_intake', models.TextField(blank=True)),
                ('smoking_status', models.TextField(blank=True)),
                ('work_schedule', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('laboratory_results_summary', models.TextField(blank=True)),
                ('readiness_to_change', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Moderate'), ('high', 'High')], max_length=10)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_assessments', to='patients.patient')),
            ],
            options={
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['patient'], name='patients_di_patient_39b23f_idx'), models.Index(fields=['assessment_type'], name='patients_di_assessm_49ca36_idx'), models.Index(fields=['assessed_at'], name='patients_di_assesse_b95ca2_idx')],
            },
        ),
    ]
