# Generated by Django 4.2.30 on 2026-07-07 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_diabetesassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesassessment',
            name='classic_hyperglycemia_symptoms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DiabetesDiagnosisSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('prediabetes', 'Prediabetes'), ('diabetes', 'Diabetes'), ('indeterminate', 'Indeterminate')], default='indeterminate', max_length=20)),
                ('confirmation_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('provisional', 'Provisional'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('fasting_plasma_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('random_plasma_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_classic_symptoms', models.BooleanField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_summary', to='patients.patient')),
                ('source_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_diagnoses', to='patients.diabetesassessment')),
                ('source_fpg_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_as_fpg', to='patients.labresult')),
                ('source_hba1c_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_as_hba1c', to='patients.labresult')),
                ('source_rpg_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_as_rpg', to='patients.labresult')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='patients_di_status_a7e161_idx'), models.Index(fields=['evaluated_at'], name='patients_di_evaluat_44b1ac_idx')],
            },
        ),
    ]
