# Generated by Django 4.2.30 on 2026-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_diabetesassessment_classic_hyperglycemia_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('physician', 'Physician'), ('dietician', 'Dietician'), ('researcher', 'Researcher')], default='patient', max_length=20),
        ),
    ]
