# Generated by Django 4.2.30 on 2026-07-08 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0016_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='approved_physicians',
            field=models.ManyToManyField(blank=True, help_text='Physicians approved by this patient to engage in physician chat posts.', related_name='approved_patient_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
