# Generated by Django 4.2.30 on 2026-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patientprofile_approved_physicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allow_all_physicians',
            field=models.BooleanField(default=False, help_text="If enabled, any physician can comment in this patient's Chat with a Physician posts."),
        ),
    ]
