# Generated by Django 4.2.30 on 2026-07-08 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_patientprofile_allow_all_physicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allow_all_dieticians',
            field=models.BooleanField(
                default=False,
                help_text="If enabled, any dietician/nutritionist can comment in this patient's dietician chat posts.",
            ),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='approved_dieticians',
            field=models.ManyToManyField(
                blank=True,
                help_text='Dieticians/nutritionists approved by this patient to engage in dietician chat posts.',
                related_name='approved_dietician_patient_profiles',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
