# Generated by Django 4.2.30 on 2026-07-08 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_patientprofile_dietician_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='issued_prescriptions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
