# Generated by Django 4.2.30 on 2026-07-21 13:30

from django.db import migrations, models


def _infer_locality(address):
    text = (address or '').strip().lower()
    if not text:
        return 'Unknown'

    urban_keywords = ['urban', 'city', 'metro', 'metropolitan', 'town']
    rural_keywords = ['rural', 'village', 'hamlet']

    if any(keyword in text for keyword in urban_keywords):
        return 'Urban'
    if any(keyword in text for keyword in rural_keywords):
        return 'Rural'
    return 'Unknown'


def _infer_region(address):
    text = (address or '').strip().lower()
    if not text:
        return 'Unknown'

    region_aliases = {
        'greater accra': 'Greater Accra',
        'accra': 'Greater Accra',
        'ashanti': 'Ashanti',
        'kumasi': 'Ashanti',
        'western north': 'Western North',
        'western': 'Western',
        'eastern': 'Eastern',
        'central': 'Central',
        'volta': 'Volta',
        'northern': 'Northern',
        'upper east': 'Upper East',
        'upper west': 'Upper West',
        'savannah': 'Savannah',
        'north east': 'North East',
        'oti': 'Oti',
        'ahafo': 'Ahafo',
        'bono east': 'Bono East',
        'bono': 'Bono',
    }

    for alias, label in region_aliases.items():
        if alias in text:
            return label

    if ',' in (address or ''):
        tail = address.split(',')[-1].strip()
        if tail:
            return tail[:64]

    if text == 'simulation dataset':
        return 'Simulated Region'

    return 'Other'


def backfill_geography(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    for patient in Patient.objects.all().iterator():
        if not patient.region:
            patient.region = _infer_region(patient.address)
        if not patient.locality_type:
            patient.locality_type = _infer_locality(patient.address)
        patient.save(update_fields=['region', 'locality_type'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_prescription_prescribed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='locality_type',
            field=models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('Peri-Urban', 'Peri-Urban'), ('Unknown', 'Unknown')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(backfill_geography, noop_reverse),
    ]
